/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlab2;

import com.sun.org.apache.bcel.internal.generic.GOTO;
import static java.lang.Math.ceil;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ProgressBar;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Casper
 */
public class arayuz extends javax.swing.JFrame implements Runnable {

    public static Thread mainthread = new Thread(new mainthread());
    public static ArrayList<Integer> dongu = new ArrayList<>();
    public static ArrayList<Integer> silinenlerindex = new ArrayList<>();
    public static ArrayList<Thread> altsunucu = new ArrayList<>();
    public static ArrayList<subthread> ozellikler = new ArrayList<>();
    public static ArrayList<JProgressBar> bars = new ArrayList<>();
    public static ArrayList<JPanel> panels = new ArrayList<>();
    public static ArrayList<JLabel> texts = new ArrayList<>();
    // public static ArrayList<JLabel> isteks= new ArrayList<>();
    public static ArrayList<Integer> removeedilenindex = new ArrayList<>();
    public static int kontrol = 0;
    public static int forbarsicin = -1;
    public static int oncekisize = 0;
    public static int sayac = 0;
    public static int tablosayaci = 2;
    public static int removeedilen = 0;
    public static int calismasay = 0;
    public static int silmesayisi = 0;
    public int saniyeliktoplam = 0;
    public int saniyelikdonen = 0;
    public int toplamgelenistek = 0;
    public int toplamdonen = 0;
    public static int kalanistek = 0;
    public static float yuzdetext = 0;
    public static int threadsayisi = 3;
    static DefaultTableModel model;
    public static int a = 0;

    /**
     * Creates new form arayuz
     */
    public arayuz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        basla = new javax.swing.JButton();
        dur = new javax.swing.JButton();
        alt1panel = new javax.swing.JPanel();
        alt1bar = new javax.swing.JProgressBar();
        alt1text = new javax.swing.JLabel();
        alt2panel = new javax.swing.JPanel();
        alt2text = new javax.swing.JLabel();
        alt2bar = new javax.swing.JProgressBar();
        mainpanel = new javax.swing.JPanel();
        yuzde = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        anlikpane = new javax.swing.JPanel();
        threadsayi = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        alt3panel = new javax.swing.JPanel();
        alt3text = new javax.swing.JLabel();
        alt3bar = new javax.swing.JProgressBar();
        alt4panel = new javax.swing.JPanel();
        alt4text = new javax.swing.JLabel();
        alt4bar = new javax.swing.JProgressBar();
        alt5panel = new javax.swing.JPanel();
        alt5text = new javax.swing.JLabel();
        alt5bar = new javax.swing.JProgressBar();
        alt6panel = new javax.swing.JPanel();
        alt6text = new javax.swing.JLabel();
        alt6bar = new javax.swing.JProgressBar();
        alt7panel = new javax.swing.JPanel();
        alt7text = new javax.swing.JLabel();
        alt7bar = new javax.swing.JProgressBar();
        alt8panel = new javax.swing.JPanel();
        alt8text = new javax.swing.JLabel();
        alt8bar = new javax.swing.JProgressBar();
        alt11panel = new javax.swing.JPanel();
        alt11text = new javax.swing.JLabel();
        alt11bar = new javax.swing.JProgressBar();
        alt9panel = new javax.swing.JPanel();
        alt9text = new javax.swing.JLabel();
        alt9bar = new javax.swing.JProgressBar();
        alt10panel = new javax.swing.JPanel();
        alt10text = new javax.swing.JLabel();
        alt10bar = new javax.swing.JProgressBar();
        alt12panel = new javax.swing.JPanel();
        alt12text = new javax.swing.JLabel();
        alt12bar = new javax.swing.JProgressBar();
        alt13panel = new javax.swing.JPanel();
        alt13text = new javax.swing.JLabel();
        alt13bar = new javax.swing.JProgressBar();
        alt14panel = new javax.swing.JPanel();
        alt14text = new javax.swing.JLabel();
        alt14bar = new javax.swing.JProgressBar();
        alt15panel = new javax.swing.JPanel();
        alt15text = new javax.swing.JLabel();
        alt15bar = new javax.swing.JProgressBar();
        alt16panel = new javax.swing.JPanel();
        alt16text = new javax.swing.JLabel();
        alt16bar = new javax.swing.JProgressBar();
        alt17panel = new javax.swing.JPanel();
        alt17text = new javax.swing.JLabel();
        alt17bar = new javax.swing.JProgressBar();
        alt18panel = new javax.swing.JPanel();
        alt18text = new javax.swing.JLabel();
        alt18bar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        goster = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));

        basla.setBackground(new java.awt.Color(0, 204, 0));
        basla.setText("BAŞLA");
        basla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslaActionPerformed(evt);
            }
        });

        dur.setBackground(new java.awt.Color(204, 0, 0));
        dur.setText("DUR");
        dur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durActionPerformed(evt);
            }
        });

        alt1panel.setBackground(new java.awt.Color(255, 255, 153));
        alt1panel.setPreferredSize(new java.awt.Dimension(249, 50));

        alt1bar.setBackground(new java.awt.Color(255, 255, 153));

        alt1text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt1text.setText("MULTİTHREAD 1");

        javax.swing.GroupLayout alt1panelLayout = new javax.swing.GroupLayout(alt1panel);
        alt1panel.setLayout(alt1panelLayout);
        alt1panelLayout.setHorizontalGroup(
            alt1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt1panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt1text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt1bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        alt1panelLayout.setVerticalGroup(
            alt1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alt1panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alt1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(alt1panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(alt1text))
                    .addComponent(alt1bar, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap())
        );

        alt2panel.setBackground(new java.awt.Color(255, 255, 153));

        alt2text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt2text.setText("MULTİTHREAD 2");

        javax.swing.GroupLayout alt2panelLayout = new javax.swing.GroupLayout(alt2panel);
        alt2panel.setLayout(alt2panelLayout);
        alt2panelLayout.setHorizontalGroup(
            alt2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt2panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt2text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt2bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alt2panelLayout.setVerticalGroup(
            alt2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt2panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt2text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt2panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt2bar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainpanel.setBackground(new java.awt.Color(255, 153, 0));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("MAIN THREAD");

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yuzde, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yuzde, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        anlikpane.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel1.setText("ANLIK OLUŞTURULAN THREAD:");

        javax.swing.GroupLayout anlikpaneLayout = new javax.swing.GroupLayout(anlikpane);
        anlikpane.setLayout(anlikpaneLayout);
        anlikpaneLayout.setHorizontalGroup(
            anlikpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anlikpaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(threadsayi, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        anlikpaneLayout.setVerticalGroup(
            anlikpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anlikpaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(threadsayi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(anlikpaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alt3panel.setBackground(new java.awt.Color(255, 255, 153));

        alt3text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt3text.setText("MULTİTHREAD 3");

        javax.swing.GroupLayout alt3panelLayout = new javax.swing.GroupLayout(alt3panel);
        alt3panel.setLayout(alt3panelLayout);
        alt3panelLayout.setHorizontalGroup(
            alt3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt3panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt3text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt3bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alt3panelLayout.setVerticalGroup(
            alt3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt3panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt3text)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(alt3panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt3bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt4panel.setBackground(new java.awt.Color(255, 255, 153));

        alt4text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt4text.setText("MULTİTHREAD 4");

        javax.swing.GroupLayout alt4panelLayout = new javax.swing.GroupLayout(alt4panel);
        alt4panel.setLayout(alt4panelLayout);
        alt4panelLayout.setHorizontalGroup(
            alt4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt4panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt4text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt4bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alt4panelLayout.setVerticalGroup(
            alt4panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt4panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt4text)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alt4panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt4bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt5panel.setBackground(new java.awt.Color(255, 255, 153));

        alt5text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt5text.setText("MULTİTHREAD 5");

        javax.swing.GroupLayout alt5panelLayout = new javax.swing.GroupLayout(alt5panel);
        alt5panel.setLayout(alt5panelLayout);
        alt5panelLayout.setHorizontalGroup(
            alt5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt5panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt5text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt5bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alt5panelLayout.setVerticalGroup(
            alt5panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt5panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt5text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt5panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt5bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt6panel.setBackground(new java.awt.Color(255, 255, 153));

        alt6text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt6text.setText("MULTİTHREAD 6");

        javax.swing.GroupLayout alt6panelLayout = new javax.swing.GroupLayout(alt6panel);
        alt6panel.setLayout(alt6panelLayout);
        alt6panelLayout.setHorizontalGroup(
            alt6panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt6panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt6text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt6bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        alt6panelLayout.setVerticalGroup(
            alt6panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt6panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt6text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alt6panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt6bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt7panel.setBackground(new java.awt.Color(255, 255, 153));

        alt7text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt7text.setText("MULTİTHREAD 7");

        javax.swing.GroupLayout alt7panelLayout = new javax.swing.GroupLayout(alt7panel);
        alt7panel.setLayout(alt7panelLayout);
        alt7panelLayout.setHorizontalGroup(
            alt7panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt7panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt7text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt7bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt7panelLayout.setVerticalGroup(
            alt7panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt7panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt7text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt7panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt7bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt8panel.setBackground(new java.awt.Color(255, 255, 153));

        alt8text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt8text.setText("MULTİTHREAD 8");

        javax.swing.GroupLayout alt8panelLayout = new javax.swing.GroupLayout(alt8panel);
        alt8panel.setLayout(alt8panelLayout);
        alt8panelLayout.setHorizontalGroup(
            alt8panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt8panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt8text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt8bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt8panelLayout.setVerticalGroup(
            alt8panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt8panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt8text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt8panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt8bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt11panel.setBackground(new java.awt.Color(255, 255, 153));

        alt11text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt11text.setText("MULTİTHREAD 11");

        javax.swing.GroupLayout alt11panelLayout = new javax.swing.GroupLayout(alt11panel);
        alt11panel.setLayout(alt11panelLayout);
        alt11panelLayout.setHorizontalGroup(
            alt11panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt11panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt11text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt11bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt11panelLayout.setVerticalGroup(
            alt11panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt11panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt11text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt11panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt11bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt9panel.setBackground(new java.awt.Color(255, 255, 153));

        alt9text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt9text.setText("MULTİTHREAD 9");

        javax.swing.GroupLayout alt9panelLayout = new javax.swing.GroupLayout(alt9panel);
        alt9panel.setLayout(alt9panelLayout);
        alt9panelLayout.setHorizontalGroup(
            alt9panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt9panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt9text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt9bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt9panelLayout.setVerticalGroup(
            alt9panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt9panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt9text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt9panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt9bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt10panel.setBackground(new java.awt.Color(255, 255, 153));

        alt10text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt10text.setText("MULTİTHREAD 10");

        javax.swing.GroupLayout alt10panelLayout = new javax.swing.GroupLayout(alt10panel);
        alt10panel.setLayout(alt10panelLayout);
        alt10panelLayout.setHorizontalGroup(
            alt10panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt10panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt10text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt10bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt10panelLayout.setVerticalGroup(
            alt10panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt10panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt10text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt10panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt10bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt12panel.setBackground(new java.awt.Color(255, 255, 153));

        alt12text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt12text.setText("MULTİTHREAD 12");

        javax.swing.GroupLayout alt12panelLayout = new javax.swing.GroupLayout(alt12panel);
        alt12panel.setLayout(alt12panelLayout);
        alt12panelLayout.setHorizontalGroup(
            alt12panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt12panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt12text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt12bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt12panelLayout.setVerticalGroup(
            alt12panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt12panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt12text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt12panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt12bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt13panel.setBackground(new java.awt.Color(255, 255, 153));

        alt13text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt13text.setText("MULTİTHREAD 13");

        javax.swing.GroupLayout alt13panelLayout = new javax.swing.GroupLayout(alt13panel);
        alt13panel.setLayout(alt13panelLayout);
        alt13panelLayout.setHorizontalGroup(
            alt13panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt13panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt13text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt13bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt13panelLayout.setVerticalGroup(
            alt13panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt13panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt13text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt13panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt13bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt14panel.setBackground(new java.awt.Color(255, 255, 153));

        alt14text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt14text.setText("MULTİTHREAD 14");

        javax.swing.GroupLayout alt14panelLayout = new javax.swing.GroupLayout(alt14panel);
        alt14panel.setLayout(alt14panelLayout);
        alt14panelLayout.setHorizontalGroup(
            alt14panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt14panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt14text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt14bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt14panelLayout.setVerticalGroup(
            alt14panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt14panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt14bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(alt14panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt14text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alt15panel.setBackground(new java.awt.Color(255, 255, 153));

        alt15text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt15text.setText("MULTİTHREAD 15");

        javax.swing.GroupLayout alt15panelLayout = new javax.swing.GroupLayout(alt15panel);
        alt15panel.setLayout(alt15panelLayout);
        alt15panelLayout.setHorizontalGroup(
            alt15panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt15panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt15text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt15bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt15panelLayout.setVerticalGroup(
            alt15panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt15panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt15text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt15panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt15bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt16panel.setBackground(new java.awt.Color(255, 255, 153));

        alt16text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt16text.setText("MULTİTHREAD 16");

        javax.swing.GroupLayout alt16panelLayout = new javax.swing.GroupLayout(alt16panel);
        alt16panel.setLayout(alt16panelLayout);
        alt16panelLayout.setHorizontalGroup(
            alt16panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt16panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt16text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt16bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt16panelLayout.setVerticalGroup(
            alt16panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt16panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt16text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt16panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt16bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt17panel.setBackground(new java.awt.Color(255, 255, 153));

        alt17text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt17text.setText("MULTİTHREAD 17");

        javax.swing.GroupLayout alt17panelLayout = new javax.swing.GroupLayout(alt17panel);
        alt17panel.setLayout(alt17panelLayout);
        alt17panelLayout.setHorizontalGroup(
            alt17panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt17panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt17text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt17bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt17panelLayout.setVerticalGroup(
            alt17panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt17panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt17text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt17panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt17bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alt18panel.setBackground(new java.awt.Color(255, 255, 153));

        alt18text.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        alt18text.setText("MULTİTHREAD 18");

        javax.swing.GroupLayout alt18panelLayout = new javax.swing.GroupLayout(alt18panel);
        alt18panel.setLayout(alt18panelLayout);
        alt18panelLayout.setHorizontalGroup(
            alt18panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt18panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt18text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt18bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alt18panelLayout.setVerticalGroup(
            alt18panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alt18panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alt18text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(alt18panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alt18bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        goster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Sunucu", "Doluluk Oranı"
            }
        ));
        jScrollPane1.setViewportView(goster);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alt6panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(alt5panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(alt4panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(alt3panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(alt1panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                        .addComponent(alt2panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(157, 157, 157)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alt11panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alt10panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alt9panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alt12panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alt8panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alt7panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alt14panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alt13panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alt18panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alt15panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alt16panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alt17panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(basla, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dur, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(anlikpane, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(basla, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dur, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(anlikpane, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(alt7panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(alt8panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(alt9panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(alt1panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alt2panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(alt3panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(alt4panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alt5panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alt6panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(alt10panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alt11panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alt12panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(alt13panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(69, 69, 69))
                                                    .addComponent(alt14panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(64, 64, 64))
                                            .addComponent(alt15panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(alt16panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58))
                                    .addComponent(alt17panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(alt18panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslaActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) goster.getModel();
        model.setRowCount(0);
        kontrol = 0;
        if (sayac == 0) {
            mainthread.start();
            altsunucu.get(0).start();
            altsunucu.get(1).start();
            Object[] eklenecek = {"Altsunucu 1", String.valueOf(ozellikler.get(0).dolulukoran)};
            Object[] eklenecek2 = {"Altsunucu 2", String.valueOf(ozellikler.get(1).dolulukoran)};
            model.addRow(eklenecek);
            model.addRow(eklenecek2);
        }
        sayac++;
    }//GEN-LAST:event_baslaActionPerformed

    private void durActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durActionPerformed
        // TODO add your handling code here:
        kontrol = 1;

    }//GEN-LAST:event_durActionPerformed

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new arayuz().setVisible(true);
                altsunucu.add(new Thread(new subthread()));
                altsunucu.add(new Thread(new subthread()));
                ozellikler.add(new subthread());
                ozellikler.add(new subthread());

                bars.add(alt1bar);
                bars.add(alt2bar);
                bars.add(alt3bar);
                bars.add(alt4bar);
                bars.add(alt5bar);
                bars.add(alt6bar);
                bars.add(alt7bar);
                bars.add(alt8bar);
                bars.add(alt9bar);
                bars.add(alt10bar);
                bars.add(alt11bar);
                bars.add(alt12bar);
                bars.add(alt13bar);
                bars.add(alt14bar);
                bars.add(alt15bar);
                bars.add(alt16bar);
                bars.add(alt17bar);
                bars.add(alt18bar);
                texts.add(alt1text);
                texts.add(alt2text);
                texts.add(alt3text);
                texts.add(alt4text);
                texts.add(alt5text);
                texts.add(alt6text);
                texts.add(alt7text);
                texts.add(alt8text);
                texts.add(alt9text);
                texts.add(alt10text);
                texts.add(alt11text);
                texts.add(alt12text);
                texts.add(alt13text);
                texts.add(alt14text);
                texts.add(alt15text);
                texts.add(alt16text);
                texts.add(alt17text);
                texts.add(alt18text);

                panels.add(alt1panel);
                panels.add(alt2panel);
                panels.add(alt3panel);
                panels.add(alt4panel);
                panels.add(alt5panel);
                panels.add(alt6panel);
                panels.add(alt7panel);
                panels.add(alt8panel);
                panels.add(alt9panel);
                panels.add(alt10panel);
                panels.add(alt11panel);
                panels.add(alt12panel);
                panels.add(alt13panel);
                panels.add(alt14panel);
                panels.add(alt15panel);
                panels.add(alt16panel);
                panels.add(alt17panel);
                panels.add(alt18panel);

                for (int i = 2; i < panels.size(); i++) {
                    panels.get(i).setVisible(false);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar alt10bar;
    public static javax.swing.JPanel alt10panel;
    private static javax.swing.JLabel alt10text;
    public static javax.swing.JProgressBar alt11bar;
    public static javax.swing.JPanel alt11panel;
    private static javax.swing.JLabel alt11text;
    public static javax.swing.JProgressBar alt12bar;
    public static javax.swing.JPanel alt12panel;
    private static javax.swing.JLabel alt12text;
    public static javax.swing.JProgressBar alt13bar;
    public static javax.swing.JPanel alt13panel;
    private static javax.swing.JLabel alt13text;
    public static javax.swing.JProgressBar alt14bar;
    public static javax.swing.JPanel alt14panel;
    private static javax.swing.JLabel alt14text;
    public static javax.swing.JProgressBar alt15bar;
    public static javax.swing.JPanel alt15panel;
    private static javax.swing.JLabel alt15text;
    public static javax.swing.JProgressBar alt16bar;
    public static javax.swing.JPanel alt16panel;
    private static javax.swing.JLabel alt16text;
    public static javax.swing.JProgressBar alt17bar;
    public static javax.swing.JPanel alt17panel;
    private static javax.swing.JLabel alt17text;
    public static javax.swing.JProgressBar alt18bar;
    public static javax.swing.JPanel alt18panel;
    private static javax.swing.JLabel alt18text;
    public static javax.swing.JProgressBar alt1bar;
    public static javax.swing.JPanel alt1panel;
    private static javax.swing.JLabel alt1text;
    public static javax.swing.JProgressBar alt2bar;
    public static javax.swing.JPanel alt2panel;
    private static javax.swing.JLabel alt2text;
    public static javax.swing.JProgressBar alt3bar;
    public static javax.swing.JPanel alt3panel;
    private static javax.swing.JLabel alt3text;
    public static javax.swing.JProgressBar alt4bar;
    public static javax.swing.JPanel alt4panel;
    private static javax.swing.JLabel alt4text;
    public static javax.swing.JProgressBar alt5bar;
    public static javax.swing.JPanel alt5panel;
    private static javax.swing.JLabel alt5text;
    public static javax.swing.JProgressBar alt6bar;
    public static javax.swing.JPanel alt6panel;
    private static javax.swing.JLabel alt6text;
    public static javax.swing.JProgressBar alt7bar;
    public static javax.swing.JPanel alt7panel;
    private static javax.swing.JLabel alt7text;
    public static javax.swing.JProgressBar alt8bar;
    public static javax.swing.JPanel alt8panel;
    private static javax.swing.JLabel alt8text;
    public static javax.swing.JProgressBar alt9bar;
    public static javax.swing.JPanel alt9panel;
    private static javax.swing.JLabel alt9text;
    private javax.swing.JPanel anlikpane;
    public static javax.swing.JButton basla;
    private javax.swing.JButton dur;
    public static javax.swing.JTable goster;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainpanel;
    public static javax.swing.JProgressBar threadsayi;
    public static javax.swing.JProgressBar yuzde;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
    }
}
